print('===== DESAFIO 04 =====')
n = input('Digite algo: ')
print('O tipo primitivo deste valor é {}'.format(type(n)))
print('Somente espaços? {}'.format(n.isspace()))
print('É um numérico? {}'.format(n.isnumeric()))
print('É um alfabético? {}'.format(n.isalpha()))
print('É alfanumérico? {}'.format(n.isalnum()))
print('Está em caixa alta? {}'.format(n.isupper()))
print('Está em caixa baixa? {}'.format(n.islower()))
print('Está capitalizado? {}'.format(n.istitle()))