print('===== DESAFIO 03 =====')
num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))
soma = int(num1 + num2)
print('A soma entre {} e {} é igual a {}.'.format(num1, num2, soma))
